Ralph Project: src/cmd_tools/cmd_send.c File Reference
cmd_send.c File Reference
#include <stdio.h>
#include <sys/socket.h>
#include <unistd.h>
#include <netinet/in.h>
#include <stdlib.h>
#include "socket_tools.h"
#include "tools.h"
#include "cmd_tools.h"
Functions
int cmd_send (unsigned char cmd, unsigned int len, int sock)
int cmd_n_data_send (unsigned char cmd, unsigned int len, unsigned char *data, int sock)
Function Documentation
cmd_n_data_send()
int cmd_n_data_send (unsigned char cmd, unsigned int len, unsigned char * data, int sock)
Definition at line 19 of file cmd_send.c.
{
    cmd_header cmd_h;
    cmd_h.magic=htonl(CMD_MAGIC);
    cmd_h.cmd=cmd;
    cmd_h.len=htonl(len);
    if(write(sock, &cmd_h, sizeof(cmd_header)) < 0 ) return -1;
    if(len>0)
        if(write(sock, data, len) < 0 ) return -1;
    return 0;
}
References cmd_header_t::cmd, CMD_MAGIC, cmd_header_t::len, cmd_header_t::magic, and sock.
Referenced by send_file().
cmd_send()
int cmd_send (unsigned char cmd, unsigned int len, int sock)
Definition at line 10 of file cmd_send.c.
{
    cmd_header cmd_h;
    cmd_h.magic=htonl(CMD_MAGIC);
    cmd_h.cmd=cmd;
    cmd_h.len=htonl(len);
    return cmd_write(&cmd_h, NULL, sock);
}
References cmd_header_t::cmd, CMD_MAGIC, cmd_write(), cmd_header_t::len, cmd_header_t::magic, and sock.
Referenced by tcp_svr_handle_cli().