Ralph Project: src/include/socket_tools/tcp_svr_handle_cli.h File Reference
tcp_svr_handle_cli.h File Reference
Functions
int handle_recv (int len, unsigned char *data)
void tcp_svr_handle_cli (int cli_sock)
Function Documentation
handle_recv()
int handle_recv (int len, unsigned char * data)
Definition at line 14 of file handle_recv.c.
{
    char tmp[128];
    char filename[1024];
    unsigned char *pt;
    int i=0;
    int fd;
    pt=data;
        while(*pt!='\0' && i <128) tmp[i++]=*pt++;
        tmp[i]='\0';
    sprintf(filename,"%s/%s",DEFAULT_DIR,tmp);
    fd=open(filename,O_CREAT | O_TRUNC| O_WRONLY,S_IRWXU|S_IRWXG|S_IRWXO);
    if(fd<0) goto error;
    write(fd,pt+1,len-strlen(tmp)-1);
    close(fd);
    return 0;
error:
    return -1;
}
References DEFAULT_DIR.
Referenced by tcp_svr_handle_cli().
tcp_svr_handle_cli()
void tcp_svr_handle_cli (int cli_sock)
Definition at line 14 of file tcp_svr_handle_cli.c.
{
    cmd_header cmd_h;
    unsigned char *data=NULL;
    if(cli_sock<0) goto error;
    if(cmd_read(&cmd_h, &data, cli_sock)<0) goto error;
    switch (cmd_h.cmd)
    {
        case CMD_RECV:
        {
            if(handle_recv(ntohl(cmd_h.len), data)<0) goto error;
            break;
        }
        default:
        {
            cmd_send(CMD_UNKNOWN, 0, cli_sock);
            break;
        }
    }
    cmd_send(CMD_OK, 0, cli_sock);
    if(data) free(data);
    close(cli_sock);
    return;
error:
    cmd_send(CMD_ERR, 0, cli_sock);
    if(data) free(data);
    close(cli_sock);
}
References cmd_header_t::cmd, CMD_ERR, CMD_OK, cmd_read(), CMD_RECV, cmd_send(), CMD_UNKNOWN, handle_recv(), and cmd_header_t::len.
Referenced by main().